### ISSUE TITLE
elasticSearch delete data  error

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2-elasticsearch#123]
```
$data = EsMidData7::find()->all();
		foreach($data as $one){
			$one->delete();
		}
```
i run this code to delete all elasticsearch data , it show error

```
clearException 'yii\elasticsearch\Exception' with message 'Elasticsearch request failed with code 400.'

in /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/Connection.php:509

Error Info:
Array
(
    [requestMethod] => DELETE
    [requestUrl] => http://192.168.0.210:9200//refer_mid_data_7/10000000108
    [requestBody] => 
    [responseCode] => 400
    [responseHeaders] => Array
        (
            [content-type] => text/plain; charset=UTF-8
            [content-length] => 77
        )

    [responseBody] => No handler found for uri [//refer_mid_data_7/10000000108] and method [DELETE]
)


```

can you help me ? thanks.

when i run 

```
EsMidData7::deleteAll(['service_date_str' => '2017-02-09']);
```

it also error:

```
clearException 'yii\elasticsearch\Exception' with message 'Elasticsearch request failed with code 400.'

in /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/Connection.php:509

Error Info:
Array
(
    [requestMethod] => GET
    [requestUrl] => http://192.168.0.210:9200/_search/scroll?scroll_id=c2Nhbjs0NTs1MTQ5ODM6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs4ODU3NToxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzg4NTc5OjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7ODg1NzY6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTs1MTUwMDA6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs1MTQ5ODU6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs1MTQ5ODQ6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs1MTQ5ODk6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs4ODU3NzoxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzg4NTgwOjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7NTE0OTk3OkFudnZOa01DU1NhenJncVlicnNSX1E7ODg1Nzg6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTs1MTQ5OTQ6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs1MTUwMDE6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs1MTQ5ODc6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs4ODU4MjoxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzUxNDk5MjpBbnZ2TmtNQ1NTYXpyZ3FZYnJzUl9ROzg4NTgxOjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7ODg1ODM6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTs1MTQ5OTE6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs4ODU4NDoxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzg4NTg1OjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7ODg1ODY6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTs4ODU4NzoxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzg4NTg4OjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7NTE0OTk5OkFudnZOa01DU1NhenJncVlicnNSX1E7ODg1ODk6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTs4ODU5MDoxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzg4NTkxOjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7ODg1OTI6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTs1MTQ5OTU6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs1MTUwMDI6QW52dk5rTUNTU2F6cmdxWWJyc1JfUTs4ODU5MzoxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzg4NTk0OjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7ODg1OTU6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTs4ODU5NjoxVkIxaEQ3V1EtNmR4aDliVU5aMGFROzUxNDk4NjpBbnZ2TmtNQ1NTYXpyZ3FZYnJzUl9ROzg4NTk3OjFWQjFoRDdXUS02ZHhoOWJVTlowYVE7NTE0OTkzOkFudnZOa01DU1NhenJncVlicnNSX1E7NTE0OTkwOkFudnZOa01DU1NhenJncVlicnNSX1E7NTE0OTk4OkFudnZOa01DU1NhenJncVlicnNSX1E7NTE0OTk2OkFudnZOa01DU1NhenJncVlicnNSX1E7NTE1MDAzOkFudnZOa01DU1NhenJncVlicnNSX1E7NTE0OTg4OkFudnZOa01DU1NhenJncVlicnNSX1E7ODg1OTg6MVZCMWhEN1dRLTZkeGg5YlVOWjBhUTsxO3RvdGFsX2hpdHM6MTU4Ow%3D%3D&scroll=1m
    [requestBody] => 
    [responseCode] => 400
    [responseHeaders] => Array
        (
            [content-type] => application/json; charset=UTF-8
            [content-length] => 319
        )

    [responseBody] => Array
        (
            [error] => Array
                (
                    [root_cause] => Array
                        (
                            [0] => Array
                                (
                                    [type] => illegal_argument_exception
                                    [reason] => Unknown parameter [_source] in request body or parameter is of the wrong type[START_ARRAY] 
                                )

                        )

                    [type] => illegal_argument_exception
                    [reason] => Unknown parameter [_source] in request body or parameter is of the wrong type[START_ARRAY] 
                )

            [status] => 400
        )

)

Stack trace:
#0 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/Connection.php(271): yii\elasticsearch\Connection->httpRequest('GET', Array, NULL, false)
#1 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/Command.php(392): yii\elasticsearch\Connection->get(Array, Array)
#2 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/BatchQueryResult.php(166): yii\elasticsearch\Command->scroll(Array)
#3 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/BatchQueryResult.php(127): yii\elasticsearch\BatchQueryResult->fetchData()
#4 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/BatchQueryResult.php(117): yii\elasticsearch\BatchQueryResult->next()
#5 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/ActiveRecord.php(580): yii\elasticsearch\BatchQueryResult->rewind()
#6 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2-elasticsearch/ActiveRecord.php(774): yii\elasticsearch\ActiveRecord::primaryKeysByCondition(Array)
#7 /www/web/datacenter/datacenter_1000/appadmin/code/Ta/console/elasticsearch/TableController.php(86): yii\elasticsearch\ActiveRecord::deleteAll(Array)
#8 [internal function]: appadmin\code\Ta\console\elasticsearch\TableController->actionClear()
#9 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#10 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#11 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2/console/Controller.php(108): yii\base\Controller->runAction('clear', Array)
#12 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('clear', Array)
#13 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('ta/elasticsearc...', Array)
#14 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('ta/elasticsearc...', Array)
#15 /www/web/datacenter/datacenter_1000/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /www/web/datacenter/datacenter_1000/yii(27): yii\base\Application->run()
#17 {main}

```

**Comment by beowulfenator** [comment]
See how your first request is accessing this url: `http://192.168.0.210:9200//refer_mid_data_7/10000000108`? Notice the double slash. Does your model have an index defined, using the `public static function index()`?
