### ISSUE TITLE
Batch insert rows

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2-elasticsearch#14]
When i iterative query and insert data. will has follow error:

~~~php
Exception 'yii\elasticsearch\Exception' with message 'Elasticsearch request fail
ed: 7 - '

in D:\www\hiscaler\bdam\vendor\yiisoft\yii2-elasticsearch\Connection.php:3
76

Error Info:
Array
(
    [requestMethod] => PUT
    [requestUrl] => http://192.168.1.222:9200/elastic/news/18408
    [requestBody] => {"id":"18408","nodeId":"183","nodeName":"璩囪▕","title":"
鑻卞浗鏀瑰杽鍦ㄥ崕绛捐瘉鏈嶅姟 灏嗗姞蹇暀瀛︾璇侀€熷害","keywords":"鑻卞浗,
鏀瑰杽,鍦ㄥ崕,绛捐瘉鏈嶅姟,灏?鍔犲揩,鐣欏绛捐瘉","description":"鐢宠鑻卞浗绛
捐瘉鐨勫悓瀛︿滑鍙互蹇€熷彇寰楃粨鏋滐紒杩戞棩锛屽氨鑻卞浗鍐呮斂閮ㄦ壙璇烘敼
鍠勫湪鍗庣璇佹湇鍔′互婊¤冻涓浗瀹㈡埛鐨勯渶瑕侊紝鑻卞浗椹讳腑鍥藉ぇ浣块璇
︾粏鍒楀嚭鏈€鏂版敼杩涙帾鏂斤細濡傚揩閫熺璇佹湇鍔°€佸湪绾跨敵璇蜂互","autho
r":"璐ｄ换缂栬緫","source":"[db:鏉ユ簮]","hitsCount":"68","publishedAt":"1393999
500","createdAt":"1397116921","updatedAt":"1393999500"}
    [responseHeaders] => Array
        (
        )

    [responseBody] =>
)

Stack trace:
#0 D:\www\hiscaler\bdam\vendor\yiisoft\yii2-elasticsearch\Connection.php(2
54): yii\elasticsearch\Connection->httpRequest('PUT', Array, '{"id":"18408","...
', false)
#1 D:\www\hiscaler\bdam\vendor\yiisoft\yii2-elasticsearch\Command.php(136)
: yii\elasticsearch\Connection->put(Array, Array, '{"id":"18408","...')
#2 D:\www\hiscaler\bdam\console\controllers\ElasticsearchController.php(11
8): yii\elasticsearch\Command->insert('elastic', 'news', Array, '18408')
#3 [internal function]: console\controllers\ElasticsearchController->actionNews(
)
#4 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\base\InlineAction.php(55): cal
l_user_func_array(Array, Array)
#5 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\base\Controller.php(151): yii\
base\InlineAction->runWithParams(Array)
#6 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\console\Controller.php(91): yi
i\base\Controller->runAction('news', Array)
#7 D:\www\hiscaler\bdam\console\controllers\ElasticsearchController.php(20
): yii\console\Controller->runAction('news')
#8 [internal function]: console\controllers\ElasticsearchController->actionIndex
()
#9 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\base\InlineAction.php(55): cal
l_user_func_array(Array, Array)
#10 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\base\Controller.php(151): yii
\base\InlineAction->runWithParams(Array)
#11 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\console\Controller.php(91): y
ii\base\Controller->runAction('', Array)
#12 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\base\Module.php(455): yii\con
sole\Controller->runAction('', Array)
#13 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\console\Application.php(161):
 yii\base\Module->runAction('elasticsearch', Array)
#14 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\console\Application.php(137):
 yii\console\Application->runAction('elasticsearch', Array)
#15 D:\www\hiscaler\bdam\vendor\yiisoft\yii2\base\Application.php(375): yi
i\console\Application->handleRequest(Object(yii\console\Request))
#16 D:\www\hiscaler\bdam\yii(27): yii\base\Application->run()
#17 {main}
~~~

Data is valid. Each time the error occurred in the different data

**Comment by cebe** [comment]
how many requests are you making? Maybe related to #8
