### ISSUE TITLE
elasticSearch 6 ， add product error：Validation Failed: 1: an id must be provided if version type or value are set;

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2-elasticsearch#167]
Elasticsearch Database Exception – yii\elasticsearch\Exception

```
Elasticsearch request failed with code 400.

Error Info: Array
(
    [requestMethod] => POST
    [requestUrl] => http://127.0.0.1:9200/fecshop_product_en/product?op_type=create
    [requestBody] => {"id":2,"product_id":"xxxx"}
    [responseCode] => 400
    [responseHeaders] => Array
        (
            [content-type] => application/json; charset=UTF-8
            [content-length] => 311
        )

    [responseBody] => Array
        (
            [error] => Array
                (
                    [root_cause] => Array
                        (
                            [0] => Array
                                (
                                    [type] => action_request_validation_exception
                                    [reason] => Validation Failed: 1: an id must be provided if version type or value are set;
                                )

                        )

                    [type] => action_request_validation_exception
                    [reason] => Validation Failed: 1: an id must be provided if version type or value are set;
                )

            [status] => 400
        )

)

```

 in /www/web/develop/fecshop/vendor/yiisoft/yii2-elasticsearch/Connection.php at line 497 

```

488489490491492493494495496497498499500501502503504505506

                    'requestBody' => $requestBody,
                    'responseCode' => $responseCode,
                    'responseHeaders' => $headers,
                    'responseBody' => $this->decodeErrorBody($body),
                ]);
            }
        } elseif ($responseCode == 404) {
            return false;
        } else {
            throw new Exception("Elasticsearch request failed with code $responseCode.", [
                'requestMethod' => $method,
                'requestUrl' => $url,
                'requestBody' => $requestBody,
                'responseCode' => $responseCode,
                'responseHeaders' => $headers,
                'responseBody' => $this->decodeErrorBody($body),
            ]);
        }
    }


```

controller:

```
<?php
/**
 * FecShop file.
 *
 * @link http://www.fecshop.com/
 * @copyright Copyright (c) 2016 FecShop Software LLC
 * @license http://www.fecshop.com/license/
 */

namespace fecshop\app\appfront\modules\Customer\controllers;

use fecshop\app\appfront\modules\AppfrontController;
use Yii;
use fecshop\queue\job\SendEmailJob;
use fecshop\elasticsearch\models\elasticSearch\Product;

/**
 * @author Terry Zhao <2358269014@qq.com>
 * @since 1.0
 */
class TestController extends AppfrontController
{
    //protected $_registerSuccessRedirectUrlKey = 'customer/account';

    public $enableCsrfValidation = false;

    /**
     * 
     */
    public function actionIndex()
    {
        Product::initLang('en');
        //Product::updateMapping();
        //Product::initLang('zh');
        //Product::updateMapping();
        $p = new Product;
        $p->id = 2;
        $p->product_id = 'xxxx';
        $p->save();
        
        
        
    }

}

```

AR model:

```
<?php
/**
 * FecShop file.
 *
 * @link http://www.fecshop.com/
 * @copyright Copyright (c) 2016 FecShop Software LLC
 * @license http://www.fecshop.com/license/
 */
namespace fecshop\elasticsearch\models\elasticSearch;

use yii\elasticsearch\ActiveRecord;
use yii\base\InvalidConfigException;
/**
 * @author Terry Zhao <2358269014@qq.com>
 * @since 1.0
 */
class Product extends ActiveRecord
{
	protected $_attr;
    protected static $_lang;
    protected static $_lang_analysis;
    
    public static $langAnalysis = [
            'zh' => 'cjk', // 中国
            'kr' => 'cjk', // 韩国
            'jp' => 'cjk', // 日本
            'en' => 'english', //
            'fr' => 'french', 
            'de' => 'german',
            'it' => 'italian',
            'pt' => 'portuguese',
            'es' => 'spanish',
            'ru' => 'russian',
            'nl' => 'dutch',
            'br' => 'brazilian',            
        ];
    /**
     * Language Analyzers
     * A set of analyzers aimed at analyzing specific language text. The following types are supported: 
     * arabic, armenian, basque, bengali, brazilian, bulgarian, catalan, cjk, czech, danish, dutch, english, finnish, french, galician, german, greek, hindi, hungarian, indonesian, irish, italian, latvian, lithuanian, norwegian, persian, portuguese, romanian, russian, sorani, spanish, swedish, turkish, thai.
     * cjk : 中日韩
     * english :英语
     * french :法语
     * german :德语
     * italian :意大利语
     * portuguese :葡萄牙语
     * spanish :西班牙语
     * russian :俄语
     * dutch :荷兰语
     * brazilian :巴西语
     * 详细参看：https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#english-analyzer
     * 
     */
    public static function initLang($lang){
        $arr = self::$langAnalysis;
        if (isset($arr[$lang]) && $arr[$lang]) {
            self::$_lang = $lang;
            self::$_lang_analysis = $arr[$lang];
        }
    }
    
	# 定义db链接
	public static function getDb()
	{
		return \Yii::$app->get('elasticsearch');
	}
    
	# db
	public static function index()
	{
		if (!self::$_lang) {
            throw new InvalidConfigException('you must run func initLang($lang) first!');
        }
        return 'fecshop_product_'.self::$_lang;
	}
	# table
	public static function type()
	{
		return 'product';
	}
	
	public function attributes()
    {
        
        if (!$this->_attr) {
            $mapConfig = self::mapConfig();
            $this->_attr = array_keys($mapConfig['properties']);
        }
        return $this->_attr;
    }
	
	public static function mapConfig(){
		if (!self::$_lang_analysis) {
            throw new InvalidConfigException('you must run func initLang($lang) first!');
        }
        $analysis = self::$_lang_analysis;
        return [
			'properties' => [
                'id'			        => ['type' => 'integer',],
                '_id'			        => ['type' => 'keyword',],
				//'product_id'			=> ['type' => 'string',"index" => "not_analyzed", "analyzer": $analysis],
				'product_id'			=> ['type' => 'keyword',],
				'name'				    => ['type' => 'text', "analyzer" => $analysis],
				'short_description'	    => ['type' => 'text', "analyzer" => $analysis],
				'description'			=> ['type' => 'text', "analyzer" => $analysis],
				
                'spu'			        => ['type' => 'keyword'],
				'sku'	                => ['type' => 'keyword'],
				'score'	                => ['type' => 'integer'],
				'status'		        => ['type' => 'integer'],
				'is_in_stock'			=> ['type' => 'integer'],
				'url_key'		        => ['type' => 'keyword'],
				'price'		            => ['type' => 'float'],
				'cost_price'			=> ['type' => 'float'],
				'special_price'			=> ['type' => 'float'],
				'special_from'		    => ['type' => 'integer'],
				'special_to'	        => ['type' => 'integer'],
				'final_price'	        => ['type' => 'float'],
				
                'image'		            => ['type' => 'text', 'index' => false],
				
				'created_at'			=> ['type' => 'integer'],
				'sync_updated_at'		=> ['type' => 'integer'],
				
			]
		];
	}
	
	public static function mapping()
    {
        return [
            static::type() => self::mapConfig(),
        ];
    }

    /**
     * Set (update) mappings for this model
     */
    public static function updateMapping(){
        $db = self::getDb();
        $command = $db->createCommand();
		if(!$command->indexExists(self::index())){
			$command->createIndex(self::index());
		}
        $command->setMapping(self::index(), self::type(), self::mapping());
    }
	
	public static function getMapping(){
		$db = self::getDb();
        $command = $db->createCommand();
		return $command->getMapping();
	}
	
	
	
}
```

Elasticsearch 6 made a lot of adjustments, a lot of grammar has changed, should be a problem with the replacement of elasticearch 6 version

**Comment by fancyecommerce** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/create-doc.html

```
PUT /website/blog/123?op_type=create
{ ... }
```

must add `id` in url ,   like  `123`

**Comment by fancyecommerce** [comment]
debug: if i change Connection.php  //  add line----> $url = $url.'/2';

```
private function createUrl($path, $options = [])
    {
        if (!is_string($path)) {
            $url = implode('/', array_map(function ($a) {
                return urlencode(is_array($a) ? implode(',', $a) : $a);
            }, $path));
            //  add line---->   $url = $url.'/2';
            if (!empty($options)) {
                $url .= '?' . http_build_query($options);
            }
        } else {
            $url = $path;
            if (!empty($options)) {
                $url .= (strpos($url, '?') === false ? '?' : '&') . http_build_query($options);
            }
        }

        return [$this->nodes[$this->activeNode]['http_address'], $url];
    }
```

then save 

```
public function actionIndex()
    {
        Product::initLang('en');
        //Product::updateMapping();
        //Product::initLang('zh');
        //Product::updateMapping();
        //$p = new Product;
        //$p->_id = 2;
        //$p->product_id = 'xxxx';
        //$p->save();
        
        $dd = Product::find()->all();
        var_dump($dd);
        
    }
```

success.  

so, it is es6 version change resuful api role,  the reason for the error

**Comment by samdark** [comment]
Are you on 2.1 branch?

**Comment by fancyecommerce** [comment]
install yii2 elasticsearch by  `"yiisoft/yii2-elasticsearch": "~2.0.0"`

elasticSearch version : 6.1

In order to do the mall search, I changed the YII-elasticsearch extension code, first cope with my current development, wait for the official fix this problem. Small bench and melon seeds are ready.

**Comment by samdark** [comment]
2.0 doesn't support 6.1 as far as I know.

**Comment by fancyecommerce** [comment]
update also have problem
```
[root_cause] => Array
                        (
                            [0] => Array
                                (
                                    [type] => mapper_parsing_exception
                                    [reason] => Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.
                                )

                        )

```

**Comment by fancyecommerce** [comment]
@samdark  Waiting for the official to fix this problem 

thank you.

**Comment by fancyecommerce** [comment]
the newly version is 2.0.4

https://github.com/yiisoft/yii2-elasticsearch/releases

how can i install  2.1?

**Comment by samdark** [comment]
By specifying `2.1@dev`.

**Comment by fancyecommerce** [comment]
add `"yiisoft/yii2-elasticsearch": "2.1.x-dev",`

composer update：
```
[root@iZ942k2d5ezZ fecshop]# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)



  - Removing yiisoft/yii2-elasticsearch (2.0.4)            
  - Installing yiisoft/yii2-elasticsearch (2.1.x-dev 3c8b09e)
    Cloning 3c8b09ee6dd736396eeeb98d24e33ea9ebc4dcea from cache

Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Writing lock file
Generating autoload files

```


also have problem：

i insert product data to elasticSearch ,and set product _id  as Es product _id

```
$elasticSearchModel = new Model();
$elasticSearchModel['_id'] = 'xxxxx';
$elasticSearchModel['sku'] = '57bab0d5f656f2940a3bf56e'
$elasticSearchModel->save();
```


error:

```
Exception 'yii\elasticsearch\Exception' with message 'Elasticsearch request failed with code 400. Response body:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."}],"type":"mapper_parsing_exception","reason":"Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."},"status":400}'

in /www/web/develop/fecshop/vendor/yiisoft/yii2-elasticsearch/Connection.php:547

Error Info:
Array
(
    [requestMethod] => POST
    [requestUrl] => http://127.0.0.1:9200/fecshop_product_en/product/57bab0d5f656f2940a3bf56e/_update
    [requestBody] => {"doc":{"status":1,"price":358,"cost_price":444,"special_price":124,"special_from":1471708800,"special_to":1570118400,"final_price":124,"sync_updated_at":1517998588,"_id":"57bab0d5f656f2940a3bf56e"}}
    [responseCode] => 400
    [responseHeaders] => Array
        (
            [content-type] => application/json; charset=UTF-8
            [content-length] => 349
        )

    [responseBody] => Array
        (
            [error] => Array
                (
                    [root_cause] => Array
                        (
                            [0] => Array
                                (
                                    [type] => mapper_parsing_exception
                                    [reason] => Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.
                                )

                        )

                    [type] => mapper_parsing_exception
                    [reason] => Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.
                )

            [status] => 400
        )

)

Stack trace:
#0 /www/web/develop/fecshop/vendor/yiisoft/yii2-elasticsearch/Connection.php(335): yii\elasticsearch\Connection->httpRequest('POST', 'http://127.0.0....', '{"doc":{"status...', false)
#1 /www/web/develop/fecshop/vendor/yiisoft/yii2-elasticsearch/Command.php(236): yii\elasticsearch\Connection->post(Array, Array, '{"doc":{"status...')
#2 /www/web/develop/fecshop/vendor/yiisoft/yii2-elasticsearch/ActiveRecord.php(541): yii\elasticsearch\Command->update('fecshop_product...', 'product', '57bab0d5f656f29...', Array, Array)
#3 /www/web/develop/fecshop/vendor/yiisoft/yii2-elasticsearch/ActiveRecord.php(505): yii\elasticsearch\ActiveRecord->updateInternal(NULL, Array)
#4 /www/web/develop/fecshop/vendor/yiisoft/yii2/db/BaseActiveRecord.php(649): yii\elasticsearch\ActiveRecord->update(true, NULL)
#5 /www/web/develop/fecshop/vendor/fancyecommerce/fecshop/services/helper/AR.php(99): yii\db\BaseActiveRecord->save()
#6 /www/web/develop/fecshop/vendor/fancyecommerce/fecshop_elasticsearch/services/search/ElasticSearch.php(81): fecshop\services\helper\AR->save(Object(fecshop\elasticsearch\models\elasticSearch\Product), Array, true)
#7 [internal function]: fecshop\elasticsearch\services\search\ElasticSearch->actionSyncProductInfo(Array, 50)
#8 /www/web/develop/fecshop/vendor/fancyecommerce/fecshop/services/Service.php(49): call_user_func_array(Array, Array)
#9 /www/web/develop/fecshop/vendor/fancyecommerce/fecshop/services/Search.php(62): fecshop\services\Service->__call('syncProductInfo', Array)
#10 [internal function]: fecshop\services\Search->actionSyncProductInfo(Array, 50)
#11 /www/web/develop/fecshop/vendor/fancyecommerce/fecshop/services/Service.php(49): call_user_func_array(Array, Array)
#12 /www/web/develop/fecshop/vendor/fancyecommerce/fecshop/app/console/modules/Product/controllers/SearchController.php(65): fecshop\services\Service->__call('syncProductInfo', Array)
#13 [internal function]: fecshop\app\console\modules\Product\controllers\SearchController->actionSyncdata('1')
#14 /www/web/develop/fecshop/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /www/web/develop/fecshop/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /www/web/develop/fecshop/vendor/yiisoft/yii2/console/Controller.php(135): yii\base\Controller->runAction('syncdata', Array)
#17 /www/web/develop/fecshop/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('syncdata', Array)
#18 /www/web/develop/fecshop/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('product/search/...', Array)
#19 /www/web/develop/fecshop/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('product/search/...', Array)
#20 /www/web/develop/fecshop/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 /www/web/develop/fecshop/yii(81): yii\base\Application->run()
#22 {main}

```

**Comment by fancyecommerce** [comment]
@samdark hope it will fix quickly , thank you.

**Comment by samdark** [comment]
Nope. Don't have time for it now, focused on 2.0.14 release.

**Comment by v-joy** [comment]
also waiting for the fix

**Comment by beowulfenator** [comment]
The reason for this error:
> Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.
