### ISSUE TITLE
Can not use ActiveRecord with rest\ActiveController

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-elasticsearch#252]
### What steps will reproduce the problem?
 
Use example model from https://github.com/yiisoft/yii2-elasticsearch/blob/master/docs/guide/usage-ar.md with standard rest controller

```
class CustomerController extends \yii\rest\ActiveController
{
    public $modelClass = 'my\models\Customer';
}
```

### What's expected?

Return the model data via API including `id` or `_id`

### What do you get instead?

```
response>
<name>Unknown Property</name>
<message>
Getting unknown property: my\models\Customer::_id
</message>
<code>0</code>
<type>yii\base\UnknownPropertyException</type>
<file>
/app/vendor/yiisoft/yii2-dev/framework/base/Component.php
</file>
<line>154</line>
<stack-trace>
<item>
#0 /app/vendor/yiisoft/yii2-dev/framework/db/BaseActiveRecord.php(298): yii\base\Component->__get('_id')
</item>
<item>
#1 /app/vendor/yiisoft/yii2-dev/framework/base/Model.php(1026): yii\db\BaseActiveRecord->__get('_id')
</item>
<item>
#2 /app/vendor/yiisoft/yii2-dev/framework/data/ActiveDataProvider.php(142): yii\base\Model->offsetGet('_id')
</item>
<item>
#3 /app/vendor/yiisoft/yii2-dev/framework/data/BaseDataProvider.php(104): yii\data\ActiveDataProvider->prepareKeys(Array)
</item>
<item>
#4 /app/vendor/yiisoft/yii2-dev/framework/data/BaseDataProvider.php(114): yii\data\BaseDataProvider->prepare()
</item>
<item>
#5 /app/vendor/yiisoft/yii2-dev/framework/rest/Serializer.php(186): yii\data\BaseDataProvider->getModels()
</item>
<item>
#6 /app/vendor/yiisoft/yii2-dev/framework/rest/Serializer.php(152): yii\rest\Serializer->serializeDataProvider(Object(yii\data\ActiveDataProvider))
</item>
<item>
#7 /app/vendor/yiisoft/yii2-dev/framework/rest/Controller.php(99): yii\rest\Serializer->serialize(Object(yii\data\ActiveDataProvider))
</item>
<item>
#8 /app/vendor/yiisoft/yii2-dev/framework/rest/Controller.php(77): yii\rest\Controller->serializeData(Object(yii\data\ActiveDataProvider))
</item>
<item>
#9 /app/vendor/yiisoft/yii2-dev/framework/base/Controller.php(159): yii\rest\Controller->afterAction(Object(yii\rest\IndexAction), Object(yii\data\ActiveDataProvider))
</item>
<item>
#10 /app/vendor/yiisoft/yii2-dev/framework/base/Module.php(528): yii\base\Controller->runAction('', Array)
</item>
<item>
#11 /app/vendor/yiisoft/yii2-dev/framework/web/Application.php(103): yii\base\Module->runAction('za/crud/api/off...', Array)
</item>
<item>
#12 /app/vendor/yiisoft/yii2-dev/framework/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
</item>
<item>
#13 /app/web/index.php(25): yii\base\Application->run()
</item>
<item>#14 {main}</item>
</stack-trace>
</response>
```

### Additional info

When I change `id` to `_id` in `attributes()` I see the records, but without the actual value for `id`, also the docs say that you should not add `_id` to `attributes`.

I'd like to use a UUID as primary key for my models.

| Q                | A
| ---------------- | ---
| Yii version       | yii 2.0.27, yiisoft/yii2-elasticsearch 2.0.5
| PHP version      | 7.3
| Operating system | Debian (Docker)

**Comment by cebe** [comment]
Could you please provide the relevant model code?

**Comment by schmunk42** [comment]
I tried with the example from the docs:

```

use yii\elasticsearch\ActiveRecord;

class Offer extends ActiveRecord
{
    /**
     * @return array the list of attributes for this record
     */
    public function attributes()
    {
        // path mapping for '_id' is setup to field 'id'
        return ['id', 'name', 'address', 'registration_date'];
    }

    /**
     * @return ActiveQuery defines a relation to the Order record (can be in other database, e.g. redis or sql)
     */
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['customer_id' => 'id'])->orderBy('id');
    }

    /**
     * Defines a scope that modifies the `$query` to return only active(status = 1) customers
     */
    public static function active($query)
    {
        $query->andWhere(['status' => 1]);
    }
}
```

`getOrders` and `active` could be removed.

**Comment by rustamwin** [comment]
I think you should use `fields` method
```php
public function fields()
{
        return [
            'id' => function () {
                 return $this->_id; // or use getter/primaryKey
            },
            //...
        ];
}
```

**Comment by schmunk42** [comment]
I can add the document ID (and name) to the output with

```
    public function fields()
    {
        return [
            'id' => function () {
                return $this->primaryKey;
            },
            'name'
            //...
        ];
    }
```

This is a step in the right direction, thank you!

I have to redefine the data I want to see in `fields`, but I guess this is fine.
Can `fields` be viewed as "computed" properties or visible data, while `attributes` is the stuff really stored in the db?

Still, I need to add `_id` to `attributes()`.

**Comment by beowulfenator** [comment]
@schmunk42 Is the issue solved?

**Comment by schmunk42** [comment]
I have no time to verify it atm, sorry.

**Comment by beowulfenator** [comment]
I've tested this and here's what I see. The controller correctly recognizes the primary key, in other words, actions like `/example-rest-model/123` does show the model with the `_id` equal to `123`. The primary key value, however, is not shown in the attributes, because it is not listed in `attributes()`, and it can not be listed there. So it needs to be added to `fields()`. There is no need to rename it to `id`, it can be just added as `_id`.

The key in Elasticsearch is called `_id` and its name can not be changed.
